import time
from ircodec.command import CommandSet

controller = CommandSet(name='LED-REMOTE', emitter_gpio=14, receiver_gpio=15)

# Add keys
print("NEXT KEY: on")
controller.add('on')
time.sleep(1)
print("NEXT KEY: off")
controller.add('off')
time.sleep(1)
print("NEXT KEY: red")
controller.add('red')
time.sleep(1)
print("NEXT KEY: red_1")
controller.add('red_1')
time.sleep(1)
print("NEXT KEY: red_2")
controller.add('red_2')
time.sleep(1)
print("NEXT KEY: red_3")
controller.add('red_3')
time.sleep(1)
print("NEXT KEY: red_4")
controller.add('red_4')
time.sleep(1)
print("NEXT KEY: green")
controller.add('green')
time.sleep(1)
print("NEXT KEY: green_1")
controller.add('green_1')
time.sleep(1)
print("NEXT KEY: green_2")
controller.add('green_2')
time.sleep(1)
print("NEXT KEY: green_3")
controller.add('green_3')
time.sleep(1)
print("NEXT KEY: green_4")
controller.add('green_4')
time.sleep(1)
print("NEXT KEY: blue")
controller.add('blue')
time.sleep(1)
print("NEXT KEY: blue_1")
controller.add('blue_1')
time.sleep(1)
print("NEXT KEY: blue_2")
controller.add('blue_2')
time.sleep(1)
print("NEXT KEY: blue_3")
controller.add('blue_3')
time.sleep(1)
print("NEXT KEY: blue_4")
controller.add('blue_4')
time.sleep(1)
print("NEXT KEY: strobe")
controller.add('strobe')
time.sleep(1)
print("NEXT KEY: fade")
controller.add('fade')
time.sleep(1)
print("NEXT KEY: smooth")
controller.add('smooth')
time.sleep(1)
print("NEXT KEY: dim_up")
controller.add('dim_up')
time.sleep(1)
print("NEXT KEY: dim_down")
controller.add('dim_down')

# Save to JSON
controller.save_as('led.json')


# Send commands
#controller.emit('')

# Remove the volume up command
#controller.remove('')

#controller = CommandSet.load('tv.json')
#controller.emit('POWER')
