# Create a CommandSet for your remote control
import time
from ircodec.command import CommandSet
controller = CommandSet(name='SAMSUNG-REMOTE', emitter_gpio=14, receiver_gpio=15)

# Add keys
print("NEXT KEY: power")
controller.add('power')
time.sleep(1)
print("NEXT KEY: source")
controller.add('source')
time.sleep(1)
print("NEXT KEY: volume_up")
controller.add('volume_up')
time.sleep(1)
print("NEXT KEY: volume_down")
controller.add('volume_down')
time.sleep(1)
print("NEXT KEY: mute")
controller.add('mute')
time.sleep(1)
print("NEXT KEY: program_up")
controller.add('program_up')
time.sleep(1)
print("NEXT KEY: program_down")
controller.add('program_down')
time.sleep(1)
print("NEXT KEY: guide")
controller.add('guide')
time.sleep(1)
print("NEXT KEY: menu")
controller.add('menu')
time.sleep(1)
print("NEXT KEY: hub")
controller.add('hub')
time.sleep(1)
print("NEXT KEY: arrow_up")
controller.add('arrow_up')
time.sleep(1)
print("NEXT KEY: arrow_left")
controller.add('arrow_left')
time.sleep(1)
print("NEXT KEY: arrow_right")
time.sleep(1)
controller.add('arrow_right')
time.sleep(1)
print("NEXT KEY: arrow_down")
controller.add('arrow_down')
time.sleep(1)
print("NEXT KEY: ok")
controller.add('ok')
time.sleep(1)
print("NEXT KEY: return")
controller.add('return')
print("NEXT KEY: exit")
controller.add('exit')

# Save to JSON
controller.save_as('samsung.json')
